export const GET_COUNTRY='GET_COUNTRY';

export const CHOOSE_COUNTRY='CHOOSE_COUNTRY';
export const CHOOSE_COUNTRY_SUCCESS='CHOOSE_COUNTRY_SUCCESS';

export const GET_COUNTRIES='GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS='GET_COUNTRIES_SUCCESS';

export const GET_WEATHER='GET_WEATHER';
export const GET_WEATHER_SUCCESS='GET_WEATHER_SUCCESS';